import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from '../components/Navbar'
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />

        <div className="flex items-center justify-center bg-zinc-50 font-sans dark:bg-dark-10">
          <main className="flex gap-5 w-full max-w-3xl flex-col items-center justify-between py-32 px-16 bg-white dark:bg-dark-10 sm:items-start">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
