import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Navbar from '@/components/ui/navbar'
import "./globals.css";
import { cookies } from "next/headers";

const roboto = Roboto({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Cookie Master",
  description: "Generated by create next app",
};

//PERF: You are at video 9, 11.Cookies - CookieMaster

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = await cookies()
  console.log('layout: ',cookie.getAll())
  const theme = cookie.get('theme')?.value ?? 'light'

  return (
    <html lang="en" data-theme={`${theme}`}>
      <body
        className={`${roboto.className} antialiased`}
      >
        <Navbar />

        {children}
      </body>
    </html>
  );
}
